name: Windows CI/CD

on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Build and test with Maven
        run: mvn -B clean test --file pom.xml

      - name: Run Cucumber tests
        run: mvn test -Dtest=RunCucumberTest

      - name: Generate JaCoCo report
        run: mvn jacoco:report

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Upload test reports
        uses: actions/upload-artifact@v3.1.0
        if: always()
        with:
          name: test-reports-windows
          path: |
            target/surefire-reports/
            target/failsafe-reports/
            target/site/jacoco/
            target/site/apidocs/
